// AUTO-GENERATED by scripts/generate-spotify-light-css.ts
import _0 from "./desktop/1718.css?inline";
import _1 from "./desktop/3059.css?inline";
import _2 from "./desktop/3938.css?inline";
import _3 from "./desktop/4173.css?inline";
import _4 from "./desktop/7004.css?inline";
import _5 from "./desktop/7016.css?inline";
import _6 from "./desktop/7501.css?inline";
import _7 from "./desktop/7567.css?inline";
import _8 from "./desktop/9235.css?inline";
import _9 from "./desktop/browse-v2.css?inline";
import _10 from "./desktop/concerts-on-tour-playlist-card.css?inline";
import _11 from "./desktop/desktop-update-notification.css?inline";
import _12 from "./desktop/dwp-error-page.css?inline";
import _13 from "./desktop/dwp-feedback-bar.css?inline";
import _14 from "./desktop/dwp-home-chips-row.css?inline";
import _15 from "./desktop/dwp-home-header.css?inline";
import _16 from "./desktop/dwp-leaderboard-component.css?inline";
import _17 from "./desktop/dwp-now-playing-bar.css?inline";
import _18 from "./desktop/dwp-offline-empty-state.css?inline";
import _19 from "./desktop/dwp-page-error-template.css?inline";
import _20 from "./desktop/dwp-panel-section.css?inline";
import _21 from "./desktop/dwp-premium-page.css?inline";
import _22 from "./desktop/dwp-premium-upsell-page.css?inline";
import _23 from "./desktop/dwp-promptedPlaylists.css?inline";
import _24 from "./desktop/dwp-socialPrompting.css?inline";
import _25 from "./desktop/dwp-tuna.css?inline";
import _26 from "./desktop/dwp-user-comments.css?inline";
import _27 from "./desktop/dwp-video-player.css?inline";
import _28 from "./desktop/dwp-video-takeover.css?inline";
import _29 from "./desktop/dwp-watch-feed-view-container.css?inline";
import _30 from "./desktop/dwp-whats-new-feed.css?inline";
import _31 from "./desktop/home-ads-container.css?inline";
import _32 from "./desktop/home-subfeed.css?inline";
import _33 from "./desktop/home-v2-section.css?inline";
import _34 from "./desktop/listening-stats-modal.css?inline";
import _35 from "./desktop/playlist-leavebehinds.css?inline";
import _36 from "./desktop/podcast-charts-hub.css?inline";
import _37 from "./desktop/podcast-charts.css?inline";
import _38 from "./desktop/this-is-playlist-concerts-carousel.css?inline";
import _39 from "./desktop/trending-near-you-toolbar.css?inline";
import _40 from "./desktop/ubi-highlighting.css?inline";
import _41 from "./desktop/web-player.css?inline";
import _42 from "./desktop/xpui-debug-window-contents.css?inline";
import _43 from "./desktop/xpui-desktop-modals.css?inline";
import _44 from "./desktop/xpui-pip-mini-player.css?inline";
import _45 from "./desktop/xpui-root-dialogs.css?inline";
import _46 from "./desktop/xpui-routes-album-prerelease.css?inline";
import _47 from "./desktop/xpui-routes-album.css?inline";
import _48 from "./desktop/xpui-routes-all-show-ads.css?inline";
import _49 from "./desktop/xpui-routes-blend.css?inline";
import _50 from "./desktop/xpui-routes-buddy-feed.css?inline";
import _51 from "./desktop/xpui-routes-collection-concert-gallery.css?inline";
import _52 from "./desktop/xpui-routes-collection-concerts.css?inline";
import _53 from "./desktop/xpui-routes-collection-episodes.css?inline";
import _54 from "./desktop/xpui-routes-collection-local-files.css?inline";
import _55 from "./desktop/xpui-routes-collection-songs.css?inline";
import _56 from "./desktop/xpui-routes-concert-campaign.css?inline";
import _57 from "./desktop/xpui-routes-concert.css?inline";
import _58 from "./desktop/xpui-routes-country-hub-section.css?inline";
import _59 from "./desktop/xpui-routes-country-hub.css?inline";
import _60 from "./desktop/xpui-routes-cultural-moment-hub.css?inline";
import _61 from "./desktop/xpui-routes-episode-more-like-this.css?inline";
import _62 from "./desktop/xpui-routes-episode.css?inline";
import _63 from "./desktop/xpui-routes-label-artists.css?inline";
import _64 from "./desktop/xpui-routes-label.css?inline";
import _65 from "./desktop/xpui-routes-offline-browse.css?inline";
import _66 from "./desktop/xpui-routes-playlist.css?inline";
import _67 from "./desktop/xpui-routes-podcast-chapter.css?inline";
import _68 from "./desktop/xpui-routes-premium-page.css?inline";
import _69 from "./desktop/xpui-routes-profile.css?inline";
import _70 from "./desktop/xpui-routes-recent-searches.css?inline";
import _71 from "./desktop/xpui-routes-recently-played.css?inline";
import _72 from "./desktop/xpui-routes-recents.css?inline";
import _73 from "./desktop/xpui-routes-search.css?inline";
import _74 from "./desktop/xpui-routes-see-all-playlist-leavebehinds.css?inline";
import _75 from "./desktop/xpui-routes-show-more-like-this.css?inline";
import _76 from "./desktop/xpui-routes-show.css?inline";
import _77 from "./desktop/xpui-routes-stage-page.css?inline";
import _78 from "./desktop/xpui-routes-taste-profile.css?inline";
import _79 from "./desktop/xpui-routes-track-v2.css?inline";
import _80 from "./desktop/xpui-routes-venues.css?inline";
import _81 from "./desktop/xpui-routes-web-settings.css?inline";
import _82 from "./desktop/xpui-routes-your-library-x.css?inline";
import _83 from "./desktop/your-sound-capsule-modal.css?inline";
import _84 from "./mobile/mobile-web-player.css?inline";
import _85 from "./mobile/mwp-artist-page.css?inline";
import _86 from "./mobile/mwp-browse-page.css?inline";
import _87 from "./mobile/mwp-download-page.css?inline";
import _88 from "./mobile/mwp-home-page.css?inline";
import _89 from "./mobile/mwp-search-landing.css?inline";
import _90 from "./mobile/mwp-search-results.css?inline";
import _91 from "./mobile/mwp-section-page.css?inline";
import _92 from "./mobile/mwp-user-profile.css?inline";
import _staticRules from "./static-rules.css?inline";

export type LightModeStylesheetOverride = {
  sourceFileName: string;
  css: string;
};

export const lightModeStylesheetOverrides = [
  { sourceFileName: "1718.css", css: _0 },
  { sourceFileName: "3059.css", css: _1 },
  { sourceFileName: "3938.css", css: _2 },
  { sourceFileName: "4173.css", css: _3 },
  { sourceFileName: "7004.css", css: _4 },
  { sourceFileName: "7016.css", css: _5 },
  { sourceFileName: "7501.css", css: _6 },
  { sourceFileName: "7567.css", css: _7 },
  { sourceFileName: "9235.css", css: _8 },
  { sourceFileName: "browse-v2.css", css: _9 },
  { sourceFileName: "concerts-on-tour-playlist-card.css", css: _10 },
  { sourceFileName: "desktop-update-notification.css", css: _11 },
  { sourceFileName: "dwp-error-page.css", css: _12 },
  { sourceFileName: "dwp-feedback-bar.css", css: _13 },
  { sourceFileName: "dwp-home-chips-row.css", css: _14 },
  { sourceFileName: "dwp-home-header.css", css: _15 },
  { sourceFileName: "dwp-leaderboard-component.css", css: _16 },
  { sourceFileName: "dwp-now-playing-bar.css", css: _17 },
  { sourceFileName: "dwp-offline-empty-state.css", css: _18 },
  { sourceFileName: "dwp-page-error-template.css", css: _19 },
  { sourceFileName: "dwp-panel-section.css", css: _20 },
  { sourceFileName: "dwp-premium-page.css", css: _21 },
  { sourceFileName: "dwp-premium-upsell-page.css", css: _22 },
  { sourceFileName: "dwp-promptedPlaylists.css", css: _23 },
  { sourceFileName: "dwp-socialPrompting.css", css: _24 },
  { sourceFileName: "dwp-tuna.css", css: _25 },
  { sourceFileName: "dwp-user-comments.css", css: _26 },
  { sourceFileName: "dwp-video-player.css", css: _27 },
  { sourceFileName: "dwp-video-takeover.css", css: _28 },
  { sourceFileName: "dwp-watch-feed-view-container.css", css: _29 },
  { sourceFileName: "dwp-whats-new-feed.css", css: _30 },
  { sourceFileName: "home-ads-container.css", css: _31 },
  { sourceFileName: "home-subfeed.css", css: _32 },
  { sourceFileName: "home-v2-section.css", css: _33 },
  { sourceFileName: "listening-stats-modal.css", css: _34 },
  { sourceFileName: "playlist-leavebehinds.css", css: _35 },
  { sourceFileName: "podcast-charts-hub.css", css: _36 },
  { sourceFileName: "podcast-charts.css", css: _37 },
  { sourceFileName: "this-is-playlist-concerts-carousel.css", css: _38 },
  { sourceFileName: "trending-near-you-toolbar.css", css: _39 },
  { sourceFileName: "ubi-highlighting.css", css: _40 },
  { sourceFileName: "web-player.css", css: _41 },
  { sourceFileName: "xpui-debug-window-contents.css", css: _42 },
  { sourceFileName: "xpui-desktop-modals.css", css: _43 },
  { sourceFileName: "xpui-pip-mini-player.css", css: _44 },
  { sourceFileName: "xpui-root-dialogs.css", css: _45 },
  { sourceFileName: "xpui-routes-album-prerelease.css", css: _46 },
  { sourceFileName: "xpui-routes-album.css", css: _47 },
  { sourceFileName: "xpui-routes-all-show-ads.css", css: _48 },
  { sourceFileName: "xpui-routes-blend.css", css: _49 },
  { sourceFileName: "xpui-routes-buddy-feed.css", css: _50 },
  { sourceFileName: "xpui-routes-collection-concert-gallery.css", css: _51 },
  { sourceFileName: "xpui-routes-collection-concerts.css", css: _52 },
  { sourceFileName: "xpui-routes-collection-episodes.css", css: _53 },
  { sourceFileName: "xpui-routes-collection-local-files.css", css: _54 },
  { sourceFileName: "xpui-routes-collection-songs.css", css: _55 },
  { sourceFileName: "xpui-routes-concert-campaign.css", css: _56 },
  { sourceFileName: "xpui-routes-concert.css", css: _57 },
  { sourceFileName: "xpui-routes-country-hub-section.css", css: _58 },
  { sourceFileName: "xpui-routes-country-hub.css", css: _59 },
  { sourceFileName: "xpui-routes-cultural-moment-hub.css", css: _60 },
  { sourceFileName: "xpui-routes-episode-more-like-this.css", css: _61 },
  { sourceFileName: "xpui-routes-episode.css", css: _62 },
  { sourceFileName: "xpui-routes-label-artists.css", css: _63 },
  { sourceFileName: "xpui-routes-label.css", css: _64 },
  { sourceFileName: "xpui-routes-offline-browse.css", css: _65 },
  { sourceFileName: "xpui-routes-playlist.css", css: _66 },
  { sourceFileName: "xpui-routes-podcast-chapter.css", css: _67 },
  { sourceFileName: "xpui-routes-premium-page.css", css: _68 },
  { sourceFileName: "xpui-routes-profile.css", css: _69 },
  { sourceFileName: "xpui-routes-recent-searches.css", css: _70 },
  { sourceFileName: "xpui-routes-recently-played.css", css: _71 },
  { sourceFileName: "xpui-routes-recents.css", css: _72 },
  { sourceFileName: "xpui-routes-search.css", css: _73 },
  { sourceFileName: "xpui-routes-see-all-playlist-leavebehinds.css", css: _74 },
  { sourceFileName: "xpui-routes-show-more-like-this.css", css: _75 },
  { sourceFileName: "xpui-routes-show.css", css: _76 },
  { sourceFileName: "xpui-routes-stage-page.css", css: _77 },
  { sourceFileName: "xpui-routes-taste-profile.css", css: _78 },
  { sourceFileName: "xpui-routes-track-v2.css", css: _79 },
  { sourceFileName: "xpui-routes-venues.css", css: _80 },
  { sourceFileName: "xpui-routes-web-settings.css", css: _81 },
  { sourceFileName: "xpui-routes-your-library-x.css", css: _82 },
  { sourceFileName: "your-sound-capsule-modal.css", css: _83 },
  { sourceFileName: "mobile-web-player.css", css: _84 },
  { sourceFileName: "mwp-artist-page.css", css: _85 },
  { sourceFileName: "mwp-browse-page.css", css: _86 },
  { sourceFileName: "mwp-download-page.css", css: _87 },
  { sourceFileName: "mwp-home-page.css", css: _88 },
  { sourceFileName: "mwp-search-landing.css", css: _89 },
  { sourceFileName: "mwp-search-results.css", css: _90 },
  { sourceFileName: "mwp-section-page.css", css: _91 },
  { sourceFileName: "mwp-user-profile.css", css: _92 },
] satisfies readonly LightModeStylesheetOverride[];

const _colorScheme = `:root,
html {
  /* Force native browser UI (scrollbars, inputs, selection) to light mode */
  color-scheme: light !important;
}
`;

export const baseLightModeCss = [_staticRules, _colorScheme].join("\n");
