import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import chroma from "chroma-js";

import { toCounterpart } from "../lib/chroma";

type Declaration = {
  name: string;
  original: string;
  mapped: string;
};

type Block = {
  selector: string;
  declarations: Declaration[];
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const snapshotCssPath = resolve(
  __dirname,
  "../snapshots/open.spotify.com_snapshot-2025-04-25_files/web-player.86a99def.css",
);
const outputCssPath = resolve(__dirname, "../assets/spotify-light.css");

const blockRegex = /([^{}]+)\{([^{}]*)\}/g;
const declarationRegex = /(--[\w-]+)\s*:\s*([^;{}]+)\s*;/g;
const sourceThemeSelector = ".encore-dark-theme";

function formatColor(input: string): string {
  const source = chroma(input);
  const mapped = toCounterpart(source).alpha(source.alpha());
  return mapped.hex("auto").toLowerCase();
}

function parseBlocks(sourceCss: string): Block[] {
  const blocks: Block[] = [];

  for (const match of sourceCss.matchAll(blockRegex)) {
    const selector = match[1]?.trim();
    const body = match[2] ?? "";

    if (!selector || !selector.includes(sourceThemeSelector)) {
      continue;
    }

    const declarations: Declaration[] = [];

    for (const declarationMatch of body.matchAll(declarationRegex)) {
      const name = declarationMatch[1]?.trim();
      const original = declarationMatch[2]?.trim();

      if (!name || !original || !chroma.valid(original)) {
        continue;
      }

      declarations.push({
        name,
        original,
        mapped: formatColor(original),
      });
    }

    if (declarations.length === 0) {
      continue;
    }

    blocks.push({ selector, declarations });
  }

  return blocks;
}

function renderCss(blocks: Block[]): string {
  const header = `/*
 * Spotify Light Mode Overrides
 * AUTO-GENERATED by scripts/generate-spotify-light-css.ts
 * Source: snapshots/open.spotify.com_snapshot-2025-04-25_files/web-player.86a99def.css
 * Strategy: read every color custom property declared under .encore-dark-theme,
 * map it through lib/chroma.ts::toCounterpart(), and re-declare it with !important.
 */`;

  const rootBlock = `:root,\nhtml {\n  /* Force native browser UI (scrollbars, inputs, selection) to light mode */\n  color-scheme: light !important;\n}`;

  const themeBlocks = blocks
    .map(({ selector, declarations }) => {
      const renderedDeclarations = declarations
        .map(
          ({ name, original, mapped }) =>
            `  ${name}: ${mapped} !important; /* ${original} → ${mapped} */`,
        )
        .join("\n");

      return `${selector} {\n${renderedDeclarations}\n}`;
    })
    .join("\n\n");

  return `${header}\n\n${rootBlock}\n\n${themeBlocks}\n`;
}

function printReport(blocks: Block[]): void {
  for (const { selector, declarations } of blocks) {
    console.log(`\n${selector}`);
    for (const { name, original, mapped } of declarations) {
      console.log(`${name} = ${original} -> ${mapped}`);
    }
  }

  const declarationCount = blocks.reduce(
    (sum, block) => sum + block.declarations.length,
    0,
  );
  console.log(`\nGenerated ${declarationCount} mapped declarations across ${blocks.length} selectors.`);
}

async function main(): Promise<void> {
  const sourceCss = await readFile(snapshotCssPath, "utf8");
  const blocks = parseBlocks(sourceCss);
  const css = renderCss(blocks);

  await writeFile(outputCssPath, css, "utf8");
  printReport(blocks);
  console.log(`\nWrote ${outputCssPath}`);
}

await main();
