import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import chroma from "chroma-js";

import { toCounterpart } from "../lib/chroma";

type Declaration = {
  property: string;
  original: string;
  mapped: string;
  kind: "custom-property" | "hardcoded-color";
};

type Block = {
  selector: string;
  declarations: Declaration[];
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const snapshotCssPath = resolve(
  __dirname,
  "../snapshots/open.spotify.com_snapshot-2025-04-25_files/web-player.86a99def.css",
);
const outputCssPath = resolve(__dirname, "../assets/spotify-light.css");

const blockRegex = /([^{}]+)\{([^{}]*)\}/g;
const declarationRegex = /([\w-]+|--[\w-]+)\s*:\s*([^;{}]+)\s*(?:;|$)/g;
const colorTokenRegex =
  /#[0-9a-f]{3,8}\b|rgba?\([^)]*\)|hsla?\([^)]*\)/gi;

function formatColor(input: string): string {
  const source = chroma(input);
  const mapped = toCounterpart(source).alpha(source.alpha());
  return mapped.hex("auto").toLowerCase();
}

function hasColorToken(value: string): boolean {
  colorTokenRegex.lastIndex = 0;
  return colorTokenRegex.test(value);
}

function mapColorsInValue(value: string): string {
  colorTokenRegex.lastIndex = 0;
  return value.replace(colorTokenRegex, (token) => {
    if (!chroma.valid(token)) {
      return token;
    }

    return formatColor(token);
  });
}

function parseDeclarations(body: string): Array<{ property: string; value: string }> {
  const declarations: Array<{ property: string; value: string }> = [];
  declarationRegex.lastIndex = 0;

  for (const match of body.matchAll(declarationRegex)) {
    const property = match[1]?.trim();
    const value = match[2]?.trim().replace(/\s*!important\s*$/i, "");

    if (!property || !value) {
      continue;
    }

    declarations.push({ property, value });
  }

  return declarations;
}

function parseCustomPropertyBlocks(sourceCss: string): Block[] {
  const blocks: Block[] = [];

  for (const match of sourceCss.matchAll(blockRegex)) {
    const selector = match[1]?.trim();
    const body = match[2] ?? "";

    if (!selector || selector.startsWith("@")) {
      continue;
    }

    const declarations = parseDeclarations(body)
      .filter(
        ({ property, value }) =>
          property.startsWith("--") && hasColorToken(value) && chroma.valid(value),
      )
      .map(({ property, value }) => ({
        property,
        original: value,
        mapped: formatColor(value),
        kind: "custom-property" as const,
      }))
      .filter(({ original, mapped }) => original !== mapped);

    if (declarations.length === 0) {
      continue;
    }

    blocks.push({ selector, declarations });
  }

  return blocks;
}

function parseHardcodedColorBlocks(sourceCss: string): Block[] {
  const blocks: Block[] = [];

  for (const match of sourceCss.matchAll(blockRegex)) {
    const selector = match[1]?.trim();
    const body = match[2] ?? "";

    if (!selector || selector.startsWith("@")) {
      continue;
    }

    const declarations = parseDeclarations(body)
      .filter(({ property, value }) => !property.startsWith("--") && hasColorToken(value))
      .map(({ property, value }) => ({
        property,
        original: value,
        mapped: mapColorsInValue(value),
        kind: "hardcoded-color" as const,
      }))
      .filter(({ original, mapped }) => original !== mapped);

    if (declarations.length === 0) {
      continue;
    }

    blocks.push({ selector, declarations });
  }

  return blocks;
}

function renderBlock({ selector, declarations }: Block): string {
  const renderedDeclarations = declarations
    .map(
      ({ property, original, mapped, kind }) =>
        `  ${property}: ${mapped} !important; /* ${kind}: ${original} → ${mapped} */`,
    )
    .join("\n");

  return `${selector} {\n${renderedDeclarations}\n}`;
}

function renderCss(customPropertyBlocks: Block[], hardcodedColorBlocks: Block[]): string {
  const header = `/*
 * Spotify Light Mode Overrides
 * AUTO-GENERATED by scripts/generate-spotify-light-css.ts
 * Source: snapshots/open.spotify.com_snapshot-2025-04-25_files/web-player.86a99def.css
 * Pass 1: map custom properties with literal color values through lib/chroma.ts::toCounterpart().
 * Pass 2: map hardcoded color literals inside normal declarations while preserving each rule selector.
 */`;

  const rootBlock = `:root,\nhtml {\n  /* Force native browser UI (scrollbars, inputs, selection) to light mode */\n  color-scheme: light !important;\n}`;

  const themeSection = [
    "/* Custom property overrides */",
    ...customPropertyBlocks.map(renderBlock),
  ].join("\n\n");

  const hardcodedSection = [
    "/* Hardcoded color overrides */",
    ...hardcodedColorBlocks.map(renderBlock),
  ].join("\n\n");

  return `${header}\n\n${rootBlock}\n\n${themeSection}\n\n${hardcodedSection}\n`;
}

function printReport(title: string, blocks: Block[]): void {
  console.log(`\n=== ${title} ===`);

  for (const { selector, declarations } of blocks) {
    console.log(`\n${selector}`);
    for (const { property, original, mapped } of declarations) {
      console.log(`${property} = ${original} -> ${mapped}`);
    }
  }

  const declarationCount = blocks.reduce(
    (sum, block) => sum + block.declarations.length,
    0,
  );
  console.log(`\n${title}: ${declarationCount} declarations across ${blocks.length} selectors.`);
}

async function main(): Promise<void> {
  const sourceCss = await readFile(snapshotCssPath, "utf8");
  const customPropertyBlocks = parseCustomPropertyBlocks(sourceCss);
  const hardcodedColorBlocks = parseHardcodedColorBlocks(sourceCss);
  const css = renderCss(customPropertyBlocks, hardcodedColorBlocks);

  await writeFile(outputCssPath, css, "utf8");

  printReport("Custom property overrides", customPropertyBlocks);
  printReport("Hardcoded color overrides", hardcodedColorBlocks);
  console.log(`\nWrote ${outputCssPath}`);
}

await main();
